linters:
  enable-all: true
linters-settings:
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
        yaml: kebab
  wsl:
    # See https://github.com/bombsimon/wsl/blob/master/doc/configuration.md for
    # documentation of available settings.
    allow-assign-and-anything: false
    allow-assign-and-call: true
    allow-cuddle-declarations: false
    allow-multiline-assign: true
    allow-separated-leading-comment: false
    allow-trailing-comment: false
    force-case-trailing-whitespace: 0
    force-err-cuddling: false
    force-short-decl-cuddling: false
    strict-append: true
  gci:
    local-prefixes: go-gen-opt/
  godox:
    keywords:
      - BUG
      - FIX
      - FIXME
      - TODO
      - bug
      - fixme
      - todo
      - fix
  gomnd:
    settings:
      mnd:
        checks: [argument,case,condition,operation,return,assign]
run:
  modules-download-mode: mod
