name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Allows to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - uses: actions/checkout@v2

      - name: linter
        uses: golangci/golangci-lint-action@v2.5.2

      - name: test
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16.3
          stable: truo
          run: go test -mod=vendor -v -race -bench=. -benchmem ./...
